#!/usr/bin/env bash
# transfers a file from our client to a server
if [ $# -lt 4 ]; then
    echo `Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY`
elif [ $# -eq 4 ]
    scp -o StrictHostChecking=no -o UserKnownHostsFile=/dev/null -q -r "$1" "$3"@"$2":~/
else
    scp -o StrictHostChecking=no -o UserKnownHostsFile=/dev/null -i "$4" -q -r "$1" "$3"@"$2":~/
fi
