#!/usr/bin/env bash
# prints 'Best School' 10 times, prints Hi if the 9th time

i=1
while [ $i -le 10 ]
    do
        if [ $i -ne 9 ]
            then
                echo 'Best School'
        fi
        if [ $i -eq 9 ]
            then
                echo 'Hi'
        fi
        i=$((i + 1))
    done
