#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
minutes=1
hours=0
while [ $hours -le 12 ]
do
      minutes=1
      echo "Hour: "$hours
      while [ $minutes -le 59 ]
        do
	        echo $minutes
	        minutes=$((minutes+1))
        done
      hours=$((hours+1))
  done
